name = "CIndices"
uuid = "5a98b6c4-18fa-405d-92b3-8277d93fed36"
authors = ["Willow Ahrens <willow.ahrens@mit.edu", "Raye Kimmerer <kimmerer@mit.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
