name = "CIndices"
uuid = "5a98b6c4-18fa-405d-92b3-8277d93fed36"
authors = ["Willow Ahrens <willow.ahrens@mit.edu", "Raye Kimmerer <kimmerer@mit.edu>"]
version = "0.2"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[targets]
test = ["Test", "SparseArrays"]
